name: test
on:
  push:
    branches:
    - "**"
  pull_request: {}
jobs:
  test:
    name: Run Test with Perl ${{ matrix.perl }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl:
          - '5.32'
          - '5.34'
          - '5.36'
          - '5.38'
          - '5.40'
          - '5.42'
          - '5.44'
        redis:
          - '6.2'
          - '7.2'
          - '7.4'
          - '8.0'
          - '8.2'
          - '8.4'
          - '8.6'
          - '8.8'
          - '8.10'
          - 'valkey-7.2'
          - 'valkey-8.0'
          - 'valkey-8.1'
          - 'valkey-9.0'
          - 'valkey-9.1'
    steps:
      - uses: actions/checkout@v2
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: |
          cpanm --quiet --installdeps --notest --with-recommends .
          perl Build.PL && ./Build build && ./Build test
